config/routes.rb
Blog::Application.routes.draw do
  root "posts#index"
  
  resources :posts
  
  namespace :admin do
    root 'posts#index'
    resources :posts        
    resource :user
    resource :session, only: [:new, :create, :destroy]
  end

  scope controller: "admin/sessions" do
    get "/login", to: :new, as: "admin_login"
    post "/login", to: :create
    get "/logout", to: :destroy
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_and_belongs_to_many :tags
    
    validates :title, presence: true
    validates :content, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_and_belongs_to_many :posts
    validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password validations: false
    validates :password, presence: true, length: { minimum: 6 }
    validates :name, presence: true
    validates :email, presence: true

    def self.auth(email, password)
        user = User.find_by email: email
        if user and user.authenticate(password) then user else false end
    end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base
    before_action :authenticate_admin!
    include Admin::SessionsHelper

    layout "admin_base"
    private
    def authenticate_admin!
        if User.count == 0
            redirect_to new_admin_user_path
        else
            unless current_user
                redirect_to admin_login_path
            end
        end
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
    def index
        @posts = Post.all
        respond_to do |format|
            format.html
            format.json {
                render json: @posts.to_json
            }
        end
    end

    def create
        post = Post.new post_params
        if tags_params
            tags_params.each do |tag_params|
                post.tags << Tag.find_or_create_by(name: tag_params[:name])
            end
        end
        if post.save
            redirect_to admin_post_path(post)
        end
    end

    def new
        @post = Post.new
    end

    def update
    end

    def edit
        @post = Post.find params[:id]
    end

    def show
        @post = Post.find params[:id]
        respond_to do |format|
            format.html
            format.json {
                render json: @post.to_json
            }
        end
    end
    
    private
    def post_params
        params.require(:post).permit(:title, :content)
    end
    def tags_params
        params[:post][:tags]
    end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  include Admin::SessionsHelper
  def new
  end

  def create
    email = params[:email]
    password = params[:password]
    user = User.auth(email, password)
    if user
        login(user)
        redirect_to admin_root_path
    else
        redirect_to admin_login_path
    end
  end

  def destroy
    
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    include Admin::SessionsHelper
    before_action :user_not_exists
    
    def new
     @user = User.new
    end
    
    def create
     user = User.new user_params
     if user.save
        login(user)
        redirect_to admin_posts_path
     else
        redirect_to action: :new
     end
    end
    
    private
    def user_not_exists
        unless User.count == 0
            redirect_to admin_posts_path
        end
    end

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        
    end

    def show
        @post = Post.find params[:id]
    end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def login(user)
        session[:user_id] = user.id
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/dashboard/_alert.html.slim
p
  = notice
p
  = alert

app/views/admin/dashboard/_global_header.html.slim
#global-header

app/views/admin/posts/_form.html.slim
= simple_form_for [:admin, @post] do |f|
    = f.input :title
    = f.input :content, as: :text
    = f.submit

app/views/admin/posts/_post_content.html.slim
section.content-preview
  header.floatingheader
  section.content-preview-content
    .wrapper ng-bind="postContent"

app/views/admin/posts/_post_list.html.slim
section.content-list
  header.floatingheader
  section.content-list-content 
    =render "posts"

app/views/admin/posts/_posts.html.slim
ol
  li ng-repeat="post in posts"
    div ng-click="showContent(post.id)" data-id="{{ post.id }}"
      h3.entry-title ng-bind="post.title"
      section.entry-meta
        span.status
          | Published At {{ post.created_at }}

app/views/admin/posts/edit.html.slim
= render 'form'

app/views/admin/posts/index.html.slim
=render "post_list"
=render "post_content"

app/views/admin/posts/new.html.slim
= render 'form'

app/views/admin/users/new.html.slim
= simple_form_for [:admin, @user], :url => admin_user_path do |f|
    = f.input :name
    = f.input :email
    = f.input :password
    = f.button :submit

app/views/layouts/admin_base.html.slim
doctype html
html ng-app="calindaDashboard"
  head
    title Blog Admin
    = stylesheet_link_tag "admin/base"
    = stylesheet_link_tag controller_path
    = javascript_include_tag "admin/base"
  body ng-controller="DashboardCtrl"
    = render 'admin/dashboard/alert'
    = render 'admin/dashboard/global_header'
    section.main-section-container
      .main-section
        = yield

app/views/layouts/application.html.slim
doctype html
html
    head
        title Blog
        == stylesheet_link_tag "application"
        == csrf_meta_tags
    body
        == yield
        == javascript_include_tag "application"